site_name: TDEP

repo_url: https://github.com/tdep-developers/tdep

copyright: 'Copyright &copy; 2023 Olle Hellman, Florian Knoop'

theme:
    name: 'material'

    palette:
        primary: white
        accent: cyan
    logo: 'media/matematico_favicon.png'
    favicon: 'media/matematico_favicon.png'
    include_search_page: false
    features:
        - navigation.tabs
        - navigation.sticky
        - navigation.instant
        - navigation.indexes

    font:
        text: Inter
        code: 'Droid Sans Mono'

nav:
  - Home: README.md
  # - Tutorial:
  #   - Overview: manual/index.md
  - Programs: 
    - program/README.md
    - Generate structure: program/generate_structure.md
    - Canonical configuration: program/canonical_configuration.md
    - Extract forceconstants: program/extract_forceconstants.md
    - Phonon dispersion relations: program/phonon_dispersion_relations.md
    - Thermal conductivity: program/thermal_conductivity.md
    - Lineshape: program/lineshape.md
    - Anharmonic free energy: program/anharmonic_free_energy.md
    - Atomic distribution: program/atomic_distribution.md
    - Pack simulation: program/pack_simulation.md
    - Samples from MD: program/samples_from_md.md
    - Dump dynamical matrices: program/dump_dynamical_matrices.md
    - Crystal structure info: program/crystal_structure_info.md
    - Refine structure: program/refine_structure.md
  - Files: files.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
