site_name: TDEP

theme:
    name: 'material'

    palette:
        primary: 'Orange'
        accent: 'Blue Grey'
    # logo: images/FV.svg
    favicon: 'media/matematico_favicon.png'
    include_search_page: false
    features:
        - navigation.tabs
        - navigation.instant

    font:
        text: 'Open Sans'
        code: 'Droid Sans Mono'

nav:
  - Home: README.md
  # - Tutorial:
  #   - Overview: manual/index.md
  - Programs:
    - Extract forceconstants: program/extract_forceconstants.md
    - Phonon dispersion relations: program/phonon_dispersion_relations.md
    - Canonical configuration: program/canonical_configuration.md
    - Anharmonic free energy: program/anharmonic_free_energy.md
    - Thermal conductivity: program/thermal_conductivity.md
    - Lineshape: program/lineshape.md
    - Atomic distribution: program/atomic_distribution.md
    - Pack simulation: program/pack_simulation.md
    - Generate structure: program/generate_structure.md
    - Crystal structure info: program/crystal_structure_info.md
    - Samples from MD: program/samples_from_md.md
    - Refine structure: program/refine_structure.md
  - Files: files.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
