#!/bin/bash
# A central place to put all the important paths. You probably have to modify this to make things work.

# the fortran compiler
FORTRAN_COMPILER="$GFORTRAN"
# required compiler flags
FCFLAGS="-ffree-line-length-none -std=f2008 -cpp -fallow-argument-mismatch"
# extra flags, for debugging and such
FCFLAGS_EXTRA=""

# optimization stuff. Go all in, sometimes
OPTIMIZATION_LEVEL="-O0"
OPTIMIZATION_SENSITIVE="-O0"

# the flag that sets the default real to a double.
DOUBLE_FLAG=  # "-fdefault-real-8"
# The flag that tells the compiler where to put .o and .mod files.
MODULE_FLAG="-J"

# the header to put in python scripts.
PYTHONHEADER="#!/usr/bin/env python"

# Which gnuplot terminal to use by default.
# Choices: aqua, qt, wxt
GNUPLOTTERMINAL="qt"

# Precompiler flags. Selecting default gnuplot terminal, and make the progressbars work.
PRECOMPILER_FLAGS="-DGP${GNUPLOTTERMINAL} -Dclusterprogressbar"

# These are the BLAS/LAPACK libraries. On OSX with gfortran, use the built-in 'framework accelerate'
PATH_TO_BLASLAPACK_LIB="-L/$PREFIX/lib"
PATH_TO_BLASLAPACK_INC="-I/$PREFIX/include"
BLASLAPACK_LIBS="-llapack -lscalapack"

# I use fftw for Fourier transforms.
PATH_TO_FFTW_LIB="-L/$PREFIX/lib"
PATH_TO_FFTW_INC="-I/$PREFIX/include"
FFTW_LIBS="-lfftw3"

# Also need MPI
PATH_TO_MPI_LIB="-L/$PREFIX/lib"
PATH_TO_MPI_INC="-I/$PREFIX/include"
MPI_LIBS="-lmpi_mpifh -lmpi"

# I also use HDF5 every now and then
PATH_TO_HDF5_LIB="-L/$PREFIX/lib"
PATH_TO_HDF5_INC="-I/$PREFIX/include"
HDF5_LIBS="-lhdf5 -lhdf5_fortran"

